/*
 * generating cosine, sine lookup table for fortran 90, .f90
 *
 * thomas@life100.cc
 *
 */
#define	__USE_BSD
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <stdint.h>

//dividing 2PI into 1000 slices
#define	PI_SLICES	(1000)

#ifndef M_PIl
# define M_PIl		3.1415926535897932384626433832795029L  /* pi */
#endif
#ifndef M_PI_2l
# define M_PI_2l	1.5707963267948966192313216916397514L  /* pi/2 */
#endif
#ifndef M_PI_4l
# define M_PI_4l	0.7853981633974483096156608458198757L  /* pi/4 */
#endif
#ifndef M_1_PIl
# define M_1_PIl	0.3183098861837906715377675267450287L  /* 1/pi */
#endif
#ifndef M_2_PIl
# define M_2_PIl	0.6366197723675813430755350534900574L  /* 2/pi */
#endif

#ifndef	M_PI
# define M_PI       3.14159265358979323846  /* pi */
#endif
#ifndef M_PI_2
# define M_PI_2     1.57079632679489661923  /* pi/2 */
#endif
#ifndef M_PI_4
# define M_PI_4     0.78539816339744830962  /* pi/4 */
#endif
#ifndef M_1_PI
# define M_1_PI		0.31830988618379067154	/* 1/pi */
#endif
#ifndef M_2_PI
# define M_2_PI		0.63661977236758134308	/* 2/pi */
#endif

/* %.*g will consume all cpus to get the possible precision and
 * it will take very long time to compute.
 * printf("sin(%d,%f)=%.*g, %.*g\n",i,x,sin(x),sin(x));
 * printf("cos(%d,%f)=%.*g, %.*g\n",i,x,cos(x),cos(x));
 * single precision : 9 digit in fraction
 * double precision : 17 digit in fraction
 * printf("sin(%d,%f)=%.9g, %.17g\n",i,x,sin(x),sin(x));
 * printf("cos(%d,%f)=%.9g, %.17g\n",i,x,cos(x),cos(x));
 */

int main(int argc, char **argv){
	printf("!.f90 : Autogenerated file by Thomas Tsai, thomas@life100.cc \n");
	printf("!.f90 : this module exports sine, consine LUT table\n");
	printf("\tmodule trigon_lut\n");
	printf("\t!dir$ attributes align:64 :: sinf_lut\n");
	printf("\t!dir$ attributes align:64 :: cosf_lut\n");
	printf("\t!dir$ attributes align:64 :: sind_lut\n");
	printf("\t!dir$ attributes align:64 :: cosd_lut\n");
	printf("\tINTEGER, PARAMETER :: PI_SLICES=%d\n", PI_SLICES);
	printf("\tREAL*8, PARAMETER :: PI=3.1415926535897932384626433832795029\n");
	printf("\tREAL*8, PARAMETER :: SLICE=3.1415926535897932384626433832795029*2.0/PI_SLICES\n");
	printf("\tREAL*4, DIMENSION(0:PI_SLICES) :: sinf_lut = (/ ");
	for(int i = 0 ; i <= PI_SLICES; i ++){
		double x = M_PIl * 2.0f * (double)i / (double)PI_SLICES;
		if(i == PI_SLICES){
			printf("%.9f /)\n",(float)sin(x));
		}else{
			printf("%.9f, ",(float)sin(x));
			if(i % 4 == 3) printf(" &\n\t");
		}
	}

	printf("\t\nREAL*4, DIMENSION(0:PI_SLICES) :: cosf_lut = (/ ");
	for(int i = 0 ; i <= PI_SLICES; i ++){
		double x = M_PIl * 2.0f * (double)i / (double)PI_SLICES;

		if(i == PI_SLICES){
			printf("%.9f /)\n",(float)cos(x));
		}else{
			printf("%.9f,",(float)cos(x));
			if(i % 4 == 3) printf(" &\n\t");
		}
	}

	printf("\n\tREAL*8, DIMENSION(0:PI_SLICES) :: sind_lut = (/ ");
	for(int i = 0 ; i <= PI_SLICES; i ++){
		double x = M_PIl * 2.0f * (double)i / (double)PI_SLICES;
		if(i == PI_SLICES){
			printf("%.17lf /)\n",(double)sin(x));
		}else{
			printf("%.17lf,",(double)sin(x));
			if(i % 4 == 3) printf(" &\n\t");
		}
	}

	printf("\n\tREAL*8, DIMENSION(0:PI_SLICES) :: cosd_lut = (/ ");
	for(int i = 0 ; i <= PI_SLICES; i ++){
		double x = M_PIl * 2.0f * (double)i / (double)PI_SLICES;

		if(i == PI_SLICES){
			printf("%.17lf /)\n",(double)cos(x));
		}else{
			printf("%.17lf,",(double)cos(x));
			if(i % 4 == 3) printf(" &\n\t");
		}
	}
	printf("\tend module trigon_lut\n");

}